version: '3.8'

services:
  wisski:
    build: .
    # Alternative: use pre-built image
    # image: ghcr.io/soda-collections-objects-data-literacy/wisski-base-image:latest
    container_name: wisski-dev
    ports:
      - "8080:80"
    # Option A: Use host network (simplest for host DB access)
    # network_mode: host
    
    # Option B: Use host gateway (recommended)
    extra_hosts:
      - "host.docker.internal:host-gateway"
    
    environment:
      # Enable debug mode
      DEBUG: "true"
      
      # Database connection to host
      DB_HOST: host.docker.internal  # Change this to your host IP if needed
      DB_PORT: 3306
      DB_USER: ${DB_USER:-drupal}
      DB_PASSWORD: ${DB_PASSWORD:-change_me}
      DB_NAME: ${DB_NAME:-drupal}
      DB_DRIVER: mysql
      
      # Drupal settings
      SITE_NAME: ${SITE_NAME:-My WissKI Dev Site}
      DRUPAL_PASSWORD: ${DRUPAL_PASSWORD:-admin123}
      DRUPAL_TRUSTED_HOST: ${DRUPAL_TRUSTED_HOST:-localhost}
      DRUPAL_USER: admin
      DOMAIN: ${DOMAIN:-localhost:8080}
      
      # Optional WissKI settings (set only if needed)
      DEFAULT_GRAPH: ${DEFAULT_GRAPH:-http://localhost/graph/}
      WISSKI_FLAVOURS: ${WISSKI_FLAVOURS:-}
      
      # Optional triplestore settings (set only if needed)
      TS_PASSWORD: ${TS_PASSWORD:-}
      TS_READ_URL: ${TS_READ_URL:-}
      TS_REPOSITORY: ${TS_REPOSITORY:-}
      TS_TOKEN: ${TS_TOKEN:-}
      TS_USERNAME: ${TS_USERNAME:-}
      TS_WRITE_URL: ${TS_WRITE_URL:-}
      
      # Optional Keycloak settings (set only if needed)
      KEYCLOAK_ADMIN_GROUP: ${KEYCLOAK_ADMIN_GROUP:-}
      KEYCLOAK_USER_GROUP: ${KEYCLOAK_USER_GROUP:-}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM:-}
      OPENID_CONNECT_CLIENT_SECRET: ${OPENID_CONNECT_CLIENT_SECRET:-}
      
    volumes:
      - wisski-files:/var/www/html/sites/default/files
      - wisski-private:/var/private-files
    
    # Uncomment to enable host network instead of port mapping
    # network_mode: host

volumes:
  wisski-files:
  wisski-private:
